# Generated by Django 4.1.3 on 2024-04-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Статус доставки',
                'verbose_name_plural': 'Статусы доставки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClientMAil', models.EmailField(max_length=254)),
                ('ClientPhone', models.IntegerField(max_length=11)),
                ('ClientAddres', models.CharField(max_length=500)),
                ('ClientName', models.TextField(max_length=500)),
                ('Name_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='delivery.deliverystatus', verbose_name='Статус доставки')),
                ('ProductID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='home.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Доставка',
                'verbose_name_plural': 'Доставки',
                'ordering': ['id'],
            },
        ),
    ]
