# Generated by Django 5.0.6 on 2024-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdelivery',
            name='ClientPhone',
            field=models.IntegerField(),
        ),
    ]
