# Generated by Django 5.0.6 on 2024-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_productdelivery_clientphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdelivery',
            name='ClientMAil',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
