# Generated by Django 5.1.6 on 2025-02-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_productdelivery_date'),
        ('home', '0013_product_product_quantity_userdesire_quantity_desire'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdelivery',
            name='ProductSize',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='home.size', verbose_name='Размер'),
            preserve_default=False,
        ),
    ]
