# Generated by Django 4.1.3 on 2024-04-04 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataTime', models.DateTimeField(verbose_name='Название')),
                ('Review', models.TextField(blank=True, max_length=1000, verbose_name='Отзыв')),
                ('ProductID', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='home.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['id'],
            },
        ),
    ]
