# Generated by Django 4.1.3 on 2024-04-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photoproduct',
            old_name='car_photo',
            new_name='product_photo',
        ),
    ]
