# Generated by Django 5.0.3 on 2024-05-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_car_photo_photoproduct_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='Product_link',
            field=models.ManyToManyField(related_name='sizes', to='home.product', verbose_name='Товар'),
        ),
    ]
