# Generated by Django 5.0.3 on 2024-05-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_size_product_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_size',
        ),
    ]
