# Generated by Django 5.0.3 on 2024-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='Product_link',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_size',
            field=models.ManyToManyField(related_name='sizes', to='home.size', verbose_name='Товар'),
        ),
    ]
