# Generated by Django 5.0.3 on 2024-05-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_size_product_link_product_product_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttype',
            old_name='Age_range',
            new_name='Type',
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_name',
            field=models.CharField(max_length=1000, verbose_name='Название Бренда'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_size',
            field=models.ManyToManyField(related_name='sizes', to='home.size', verbose_name='Размер'),
        ),
    ]
