# Generated by Django 5.0.3 on 2024-05-16 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_age_range_producttype_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='TypeGender',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.PROTECT, to='home.gender', verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
