# Generated by Django 5.0.3 on 2024-05-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_producttype_typegender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.BooleanField(verbose_name='Распродажа'),
        ),
    ]
