# Generated by Django 5.0.3 on 2024-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_sale',
            field=models.BooleanField(default=1, verbose_name='Распродажа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_price',
            field=models.CharField(max_length=20, verbose_name='Цена'),
        ),
    ]
