# Generated by Django 5.0.6 on 2024-06-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_product_product_sale_alter_product_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textile_name', models.CharField(max_length=1000, verbose_name='Название ткани')),
            ],
            options={
                'verbose_name': 'Ткань',
                'verbose_name_plural': 'Ткани',
                'ordering': ['id'],
            },
        ),
    ]
