# Generated by Django 5.0.6 on 2024-06-10 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_textile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_textile',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.PROTECT, to='home.textile', verbose_name='Ткань'),
            preserve_default=False,
        ),
    ]
