# Generated by Django 5.0.6 on 2024-09-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_product_availabilityinstock_userdesire'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_quantity',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdesire',
            name='quantity_desire',
            field=models.IntegerField(blank=True, default=1, verbose_name='Количество желаемого'),
            preserve_default=False,
        ),
    ]
